# Generated by Django 4.1.2 on 2022-11-22 13:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_edit', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('categoria', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('image_categoria', models.ImageField(upload_to='categoria/', verbose_name='Imagen Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_edit', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_edit', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Blog')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Blog')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo del Blog')),
                ('nosotros', models.TextField(verbose_name='Nosotros del Blog')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_add', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_edit', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('titulo', models.CharField(max_length=150, unique=True, verbose_name='Título del Post')),
                ('meta', models.CharField(max_length=150, unique=True, verbose_name='Meta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen_post', models.ImageField(max_length=255, upload_to='imagenes/', verbose_name='Imagen Referencial')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado / No Publicado')),
                ('fecha_publicacion', models.DateField(auto_now=True, verbose_name='Fecha de Publicación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
